project:
  type: website

website:
  title: "Yaling"
  image: "Name_logo.png"
  favicon: "Web_image.jpeg"
  page-navigation: true
  page-footer: Copyright 2024![](Name_Logo(1).png){fig-alt="Name_logo(1)" width=100px}
  navbar:
    logo: "Name_logo.png"
    title: false
    collapse-below: lg
    search: true
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
         
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: zephyr
    mainfont: Georgia
    fontsize: 1.2em
    linestretch: 2
    margin-left: 5% 0
    css: styles.css
    toc: true

editor: visual

