project:
  type: website

website:
  favicon: "images/Web_logo.png"
  site-url: https://isss608-vaa-wyaling.netlify.app
  title: "VAA-Yaling"
  navbar:
    title: false
    logo: "images/Name_logo.png"
    pinned: true
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "1. A Layered Grammar of Graphics: ggplot2 methods"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "3"
        - text: "4"
        - text: "5"
        - text: "6"
        - text: "7"
        - text: "8"
        - text: "9"
    - text: "In-class Exercise"
      menu:
        - text: "1. Importing Data"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "2"
        - text: "3"
        - text: "4"
        - text: "5"
        - text: "6"
        - text: "7"
        - text: "8"
        - text: "9"
    - text: "Take-home Exercise"
      menu:
        - text: "1. Creating Data Visualisation Beyond Default"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "2"
        - text: "3"
    - text: "Project"
      menu:
        - text: "introduction"
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    tools:
      - icon: linkedin
      - icon: github
        menu:
          - text: Source Code
          - text: Report a bug
          
  sidebar:
    contents: auto
    location: sidebar
    title: "Yaling's Journey"
    style: "docked"
    search: true
    background: secondary
    foreground: primary
    alignment: left
    pinned: false


  search: 
    location: sidebar
    type: overlay
    copy-button: true

  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    border: true
    right: Copyright 2024![](images/Name_Logo(1).png){width=100px}


format:
  html:
    toc: true
    theme: cerulean
    mainfont: Comic Sans MS
    fontsize: 1.2em
    linestretch: 1.5
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    html-math-method: katex
    css: styles.css
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-line-numbers: true

editor: visual

