project:
  type: website

website:
  favicon: "images/Web_logo.png"
  site-url: https://isss608-vaa-wyaling.netlify.app
  title: "Yaling's VAA journey"
  navbar:
    title: false
    logo: "images/Name_logo.png"
    pinned: true
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "1. A Layered Grammar of Graphics: ggplot2 methods"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "2. Beyond ggplot2 Fundamentals"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "3. Programming Interactive Data Visualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03(1).html"
        - text: "4. Programming Animated Statistical Graphics with R"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03(2).html"
        - text: "5"
        - text: "6"
        - text: "7"
        - text: "8"
        - text: "9"
    - text: "In-class Exercise"
      menu:
        - text: "1. Importing Data in R"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "2. Tableau01: Make a Chart"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
        - text: "3. Tableau02: Make Dashboard & Story"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
        - text: "4"
        - text: "5"
        - text: "6"
        - text: "7"
        - text: "8"
        - text: "9"
    - text: "Take-home Exercise"
      menu:
        - text: "1. Analysis of Singaporean Students’ Performance"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "2. Peer Critique & DataVis Makeover"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"        
        - text: "3"
    - text: "Project"
      menu:
        - text: "introduction"
    right:
      - text: "Home"
        href: index.qmd
      #- text: "About"
        #href: about.qmd
    tools:
      - icon: linkedin
      - icon: envelope-at
        href: https://mail.google.com/mail/u/0/?view=cm&fs=1&to=yalingsayhi@gmail.com
      - icon: github
        menu:
          - text: Source Code
          - text: Report a bug
          

  sidebar:
    location: sidebar
    style: "docked"
    search: true
    background: secondary 
    foreground: primary
    alignment: left
    pinned: true
    contents:
      - section: "Hands-on Exercise"
        contents: Hands-on_Ex/*/*.qmd
      - section: "In-class Exercise"
        contents: In-class_Ex/*/*.qmd
      - section: "Take-home Exercise"
        contents: Take-home_Ex/*/*.qmd       

  search: 
    location: sidebar
    type: overlay
    copy-button: true

  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    border: true
    right: Copyright 2024![](images/Name_logo(1).png){width=100px}


format:
  html:
    toc: true
    theme: cerulean
    mainfont: Times New Roman
    fontsize: 1 em
    color: black
    linestretch: 1.5
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem

    css: styles.css
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-line-numbers: true

editor: visual

