project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
         
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: zephyr
    mainfont: Georgia
    fontsize: 1.2em
    linestretch: 2
    margin-left: 5% 0
    css: styles.css
    toc: true

editor: visual

