---
title: "1 Now You See It!"
title-block-banner: "#F0FFFF"
author: "Wang Yaling"
date: "Jan 13, 2024"
date-modified: last-modified
date-format: medium
excute:
  eval: true
  echo: true
  warning: false
editor: visual
abstract: 
    This document is the learning result for in-class exercise 1.
---

## Loading R packages

In this hands-on exercise, two R packages will be used. They are: [`tidyverse`](http://www.tidyverse.org), and [`haven`](https://haven.tidyverse.org/reference/index.html).

The code chunk used is as follows:

```{r}
pacman::p_load(tidyverse,haven)
```

## Importing PISA sata

The code chunk below uses [`read_sas()`](https://haven.tidyverse.org/reference/read_sas.html) of haven to import [PISA](https://www.oecd.org/pisa/data/2022database/) data into environment.

```{r}
#| eval: false
stu_qqq<- read_sas("data/cy08msp_stu_qqq.sas7bdat")

```

Filter the table using `filter()`

```{r}
#| eval: false
stu_qqq_SG <- stu_qqq %>%
  filter(CNT == "SGP")
```

Write records into the data file.

```{r}
#| eval: false
write_rds(stu_qqq_SG, "data/stu_qqq_SG.rds")
```

```{r}
stu_qqq_SG <- 
  read_rds("data/stu_qqq_SG.rds")
```
